### ISSUE TITLE
Raspberry Pi 3 support?

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-access-point#2]
Please clarify if this repo is compatible with Raspberry Pi 3.  Does the Open WRT binary need to be rebuilt for Raspberry Pi 3?   We only have 3s in our lab.  No 2s.

**Comment by jzehler** [comment]
We ran into same issue.  The prebuilt Pi 2 binary hangs on the rainbow screen when it first boots on a Pi 3.  If you run `make menuconfig`, you can change the subtarget to BCM2710 based boards and the target profile to Raspberry Pi 3 Model B.  However, it appears you need access to some private repos to build it.  I opened another support issue regarding the private repos dependency since i don't have access.

**Comment by dlfryar-zz** [comment]
@devran01 any chance this project would be converted to the LEDE Project in order to pick up Raspberry Pi 3 model B support?

https://lede-project.org

**Comment by urutva** [comment]
@dlfryar Raspberry Pi 2 model B is already supported. Do you mean Raspberry Pi 3? If so, the support for Raspberry Pi 3 will be added in the next release.

We do not have plans to port this project to LEDE.

**Comment by dlfryar-zz** [comment]
Sorry, typo, yes Raspberry Pi 3 model B.

**Comment by urutva** [comment]
The support for Raspberry Pi 3 will be added in the next release.
